version: "3.9"
services:
  postgres:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecret
      - POSTGRES_DB=simplebank
    networks:
      - simplebank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:mysecret@postgres:5432/simplebank?sslmode=disable
      - DB_DRIVER=postgres
      - HTTP_SERVER_ADDRESS=0.0.0.0:8080
      - ACCESS_TOKEN_DURATION=10m
      - TOKEN_SYMMETRIC_KEY=cae1X53au6agHqAOulzCRhgDr0BG52yv
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
    networks:
      - simplebank
networks:
  simplebank:
    driver: bridge
